# Generated by Django 3.2.8 on 2021-10-07 12:21

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique_for_date='date_posted', verbose_name='title')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, default='defaults/blogs/blog_default.jpeg', force_format='JPEG', keep_meta=True, null=True, quality=99, size=[950, 350], upload_to='blogs/articles')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL Identifier', verbose_name='Slug')),
                ('content', models.TextField(verbose_name='content')),
                ('is_locked', models.BooleanField(default=False, help_text='Determine if article can be modified', verbose_name='is locked')),
                ('is_hidden', models.BooleanField(default=False, help_text='Determine if article can be listed', verbose_name='is hidden')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL Identifier', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('is_hidden', models.BooleanField(default=False, help_text='Determine if article can be listed', verbose_name='is hidden')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.article', verbose_name='Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='blogs.post')),
            ],
        ),
    ]
