# Generated by Django 3.2.8 on 2021-10-07 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('unit', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.CharField(choices=[('f', 'first semester'), ('s', 'second semester')], default='f', help_text='semester course is been taught', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designate degree title as either Bsc, Msc, PhD', max_length=5, verbose_name='Degree type')),
                ('name', models.CharField(help_text='E.G Pure and Applied Chemistry', max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date Degree was started in the institution')),
                ('preview', models.ImageField(blank=True, default='defaults/academics/awards.png', upload_to='academics/degree')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('short_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Programme name')),
                ('slug', models.SlugField(help_text='Unique URL Identifier', unique=True, verbose_name='URL Identifier')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date Programme was started', verbose_name='Programme start date')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.course')),
            ],
        ),
    ]
