# Generated by Django 3.2.8 on 2021-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.TextField(blank=True, default='State Specialist Hospital, Potiskum', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, default='2348097799871', max_length=255),
        ),
    ]
