# Generated by Django 3.2.8 on 2021-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20211008_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, default='http://www.facebook.com/aderibigbep'),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, default='http://www.instagram.com/its_adepeter'),
        ),
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.URLField(blank=True, default='http://www.linkedin.com/in/adepeter'),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter',
            field=models.URLField(blank=True, default='http://www.twitter.com/aderibigbep'),
        ),
    ]
