# Generated by Django 3.2.8 on 2021-10-07 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('is_closed', models.BooleanField(default=False, help_text='Is job ads still open for application submission', verbose_name='Close application')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_closing', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
