# Generated by Django 3.2.8 on 2021-10-07 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
        ('academics', '0002_initial'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofdepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultymembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_memberships', to='faculties.department'),
        ),
        migrations.AddField(
            model_name='facultymembership',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_memberships', to='faculties.faculty'),
        ),
        migrations.AddField(
            model_name='facultymembership',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='settings.position'),
        ),
        migrations.AddField(
            model_name='facultymembership',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculties.dean'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faculties.faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='programmes',
            field=models.ManyToManyField(to='academics.Programme'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='staffs',
            field=models.ManyToManyField(related_name='members', through='faculties.FacultyMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='faculties.faculty'),
        ),
        migrations.AddField(
            model_name='dean',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deans', to='faculties.faculty', verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='dean',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculties.headofdepartment',),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculties.hod'),
        ),
    ]
