# Generated by Django 3.2.8 on 2021-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
        migrations.CreateModel(
            name='VisitorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('has_visited', models.BooleanField(default=False)),
            ],
        ),
    ]
