# Generated by Django 3.2.8 on 2021-10-07 12:21

from django.db import migrations, models
import django_resized.forms
import precise_bbcode.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('description', precise_bbcode.fields.BBCodeTextField(default='Yet to define an event', no_rendered_field=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='defaults/events/events_default.jpg', force_format='JPEG', help_text='Event cover image', keep_meta=True, null=True, quality=99, size=[950, 350], upload_to='events', verbose_name='image')),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
